[plugins]
"rocks.nvim" = "2.35.2"
"rocks-config.nvim" = "2.1.4"
"rocks-git.nvim" = "2.0.0"
"which-key.nvim" = "3.5.0"
"mason.nvim" = "1.10.0"
"conform.nvim" = "6.0.0"
"nui.nvim" = "0.3.0"
nvim-web-devicons = "0.100"
nvim-surround = "2.1.5"
rustaceanvim = "4.26.1"
"session.nvim" = "2.0.1"
"mini.starter" = "scm"
"mini.pick" = "scm"
"mini.hipatterns" = "scm"
"mini.diff" = "scm"
"mini.ai" = "scm"
nvim-autopairs = "scm"
"plenary.nvim" = "scm"
treesj = "scm"
"lspkind.nvim" = "scm"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.vim-kitty-navigator]
git = "knubie/vim-kitty-navigator"

[plugins.nvim-recorder]
git = "chrisgrieser/nvim-recorder"

[plugins.vim-pasta]
git = "ku1ik/vim-pasta"

[plugins.vim-dotenv]
git = "tpope/vim-dotenv"

[plugins.vim-kitty]
git = "fladson/vim-kitty"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
branch = "main"

[config]
plugins_dir = "plugins/"
