# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.26.0"
"mini.starter" = "0.9.0"
"rocks-config.nvim" = "1.5.0"
"which-key.nvim" = "1.6.0"
"mason.nvim" = "1.10.0"
"conform.nvim" = "5.6.0"
"rocks-git.nvim" = "1.4.0"
"heirline.nvim" = "1.0.3"
"mini.pick" = "0.12.0"
"nui.nvim" = "0.3.0"
nvim-web-devicons = "0.99"
"todo-comments.nvim" = "1.2.0"
nvim-surround = "2.1.5"

nvim-autopairs = "scm"
"plenary.nvim" = "scm"
"mini.diff" = "scm"

tree-sitter-php = "scm"
tree-sitter-php_only = "scm"
tree-sitter-html = "scm"
tree-sitter-html_tags = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-ecma = "scm"
tree-sitter-query = "scm"
tree-sitter-toml = "scm"

nvim-cmp = { git = "hrsh7th/nvim-cmp" }
cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
cmp-path = { git = "hrsh7th/cmp-path" }
cmp-buffer = { git = "hrsh7th/cmp-buffer" }
"lspkind.nvim" = { git = "onsails/lspkind.nvim" }
vim-kitty-navigator = { git = "knubie/vim-kitty-navigator" }
nvim-recorder = { git = "chrisgrieser/nvim-recorder" }
vim-pasta = { git = "ku1ik/vim-pasta" }
vim-repeat = { git = "tpope/vim-repeat" }
vim-dotenv = { git = "tpope/vim-dotenv" }
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter", branch = "main" }
"nvim-colorizer.lua" = { git = "norcalli/nvim-colorizer.lua" }

[config]
plugins_dir = "plugins/"
